model_type: 1
input_nc: 3
patch_size: 64

#batch size for each GPU RAM available
#24GB, 32GB, 10 - 12GB, 8GB
batch_size: [256, 256, 64, 64] #amount of images to accumulate before backprop
load_size: [256, 256, 64, 64] #amount of images to load in GPU. load_size <= batch_size

num_blocks: 6
weight_decay: 0.0
dropout_rate: 0.0
augment_key: "none"
use_tanh: True
use_cbam: False

g_lr: 0.0002
d_lr: 0.0005
min_epochs: 15
max_epochs: 20

dataset_version: "v01_fcity"
dataset_a_repeats: 10
dataset_b_repeats: 10




