model_type: 3 #1 = vanilla cycle gan, 2 = u-net, 3 = ffa-net
input_nc: 3
patch_size: 64

batch_size: 512 #amount of images to accumulate before backprop
load_size: 512 #amount of images to load in GPU. load_size <= batch_size

num_blocks: 6
weight_decay: 0.0
dropout_rate: 0.0
augment_key: "none"

g_lr: 0.0002
d_lr: 0.0005
min_epochs: 15
max_epochs: 20

dataset_version: "v01_fcity"
dataset_repeats: 5

hyperparams:
  1:
    l1_weight: 1.0
    lpip_weight: 1.0
    adv_weight: 1.0
    is_bce: 0

  2:
    l1_weight: 1.0
    lpip_weight: 1.0
    adv_weight: 1.0
    is_bce: 1

  3:
    l1_weight: 10.0
    lpip_weight: 1.0
    adv_weight: 1.0
    is_bce: 0

  4:
    l1_weight: 10.0
    lpip_weight: 1.0
    adv_weight: 1.0
    is_bce: 1




